### ISSUE TITLE
OSX - Vim grammar system events (applescript) error

### ISSUE THREAD

**Issue by dylan-chong** [dictation-toolbox/aenea-grammars#8]
This error shows up in the Natlink console on the VM when I am speaking with the vim grammar.

```
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\dragonfly\engines\engine_natlink.py", line 225, in begin_callback
    self.grammar.process_begin(executable, title, handle)
  File "C:\Python27\lib\site-packages\dragonfly\grammar\grammar_base.py", line 361, in process_begin
    r.process_begin(executable, title, handle)
  File "C:\Python27\lib\site-packages\dragonfly\grammar\rule_base.py", line 183, in process_begin
    self._process_begin()
  File "C:\NatLink\NatLink\MacroSystem\_vocabulary.py", line 51, in _process_begin
    aenea.vocabulary.refresh_vocabulary()
  File "C:\NatLink\NatLink\MacroSystem\aenea\vocabulary.py", line 131, in refresh_vocabulary
    _rebuild_lists('dynamic')
  File "C:\NatLink\NatLink\MacroSystem\aenea\vocabulary.py", line 175, in _rebuild_lists
    for (c, _) in _vocabulary_inhibitions.get(tag, [])):
  File "C:\NatLink\NatLink\MacroSystem\aenea\vocabulary.py", line 175, in <genexpr>
    for (c, _) in _vocabulary_inhibitions.get(tag, [])):
  File "C:\NatLink\NatLink\MacroSystem\aenea\wrappers.py", line 212, in matches
    return context.matches(executable, title, handle)
  File "C:\NatLink\NatLink\MacroSystem\aenea\proxy_contexts.py", line 146, in matches
    return self._reduce_matches(self._check_properties())
  File "C:\NatLink\NatLink\MacroSystem\aenea\proxy_contexts.py", line 107, in _check_properties
    properties = _get_context()
  File "C:\NatLink\NatLink\MacroSystem\aenea\proxy_contexts.py", line 76, in _get_context
    _refresh_server()
  File "C:\NatLink\NatLink\MacroSystem\aenea\proxy_contexts.py", line 63, in _refresh_server
    _last_context = aenea.communications.server.get_context()
  File "C:\NatLink\NatLink\MacroSystem\aenea\communications.py", line 108, in call
    return self._execute_batch([(meth, a, kw)])
  File "C:\NatLink\NatLink\MacroSystem\aenea\communications.py", line 87, in _execute_batch
    batch[0][0])(*batch[0][1], **batch[0][2])
  File "C:\Python27\lib\site-packages\jsonrpclib\jsonrpc.py", line 290, in __call__
    return self.__send(self.__name, kwargs)
  File "C:\Python27\lib\site-packages\jsonrpclib\jsonrpc.py", line 238, in _request
    check_for_errors(response)
  File "C:\Python27\lib\site-packages\jsonrpclib\jsonrpc.py", line 567, in check_for_errors
    raise ProtocolError((code, message))
jsonrpclib.jsonrpc.ProtocolError: (-32603, u'Server error:   File "/usr/local/lib/python2.7/site-packages/applescript/__init__.py", line 65, in _unpackresult | ScriptError: System Events got an error: Can?t get window 1 of process "iTerm2" whose value of attribute "AXMain" = true. Invalid index. (-1719) app=u\'System Events\' range=404-409')
```

In case I haven't set things up right, after setting up aenea according to the [instructions](https://github.com/dictation-toolbox/aenea) I copied the `_vim.py` and `vocabulary_config` into my `C:\NatLink\NatLink\MacroSystem` folder on the VM, then restarted Dragon.

**Comment by dylan-chong** [comment]
It appears that the dictation just doesn't work when typing into iTerm 2. It works typing into MacVim
